'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { TELEMETRY_STATS } from '@/content/club-data';
import { Activity, ShieldAlert, Cpu, Sparkles, TrendingUp } from 'lucide-react';

export const ImpactTelemetry: React.FC = () => {
  return (
    <section id="telemetry" className="relative py-24 bg-white border-y border-slate-200/80 overflow-hidden">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Section Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-6">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#E8F7EE] border border-[#3FA85B]/30 text-[#0F4C2A] text-xs font-mono mb-3 font-bold">
              <Activity className="w-3.5 h-3.5 text-[#3FA85B]" />
              <span>LIVE CAMPUS TELEMETRY</span>
            </div>
            <h2 className="text-3xl sm:text-5xl font-black text-slate-900 tracking-tight uppercase">
              MEASURABLE <span className="text-[#3FA85B]">ZERO IMPACT</span>
            </h2>
          </div>

          <p className="text-sm font-sans text-slate-600 max-w-md">
            Real-world metrics generated by ISIMS student researchers, social innovators, and green tech engineers in Sfax.
          </p>
        </div>

        {/* Telemetry Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {TELEMETRY_STATS.map((stat, idx) => {
            return (
              <motion.div
                key={stat.id}
                initial={{ opacity: 0, y: 25 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-50px' }}
                transition={{ duration: 0.4, delay: idx * 0.1 }}
                className="clean-card clean-card-hover p-6 sm:p-8 rounded-3xl relative overflow-hidden group"
              >
                {/* Top indicator */}
                <div className="flex items-center justify-between text-xs font-mono text-slate-400 mb-6">
                  <span>TELEMETRY 0{idx + 1}</span>
                  <div className="w-2 h-2 rounded-full bg-[#3FA85B]/60 group-hover:bg-[#3FA85B] transition-colors" />
                </div>

                {/* Metric */}
                <div className="text-4xl sm:text-5xl font-black font-mono text-slate-900 tracking-tight">
                  {stat.prefix || ''}
                  {stat.value.toLocaleString()}
                  <span className="text-[#3FA85B] text-2xl sm:text-3xl ml-1">{stat.suffix}</span>
                </div>

                {/* Stat Label & Description */}
                <div className="mt-4 space-y-1">
                  <div className="text-base font-bold text-slate-900">
                    {stat.label}
                  </div>
                  <p className="text-xs text-slate-500 font-sans leading-relaxed">
                    {stat.caption}
                  </p>
                </div>

                <div className="absolute bottom-0 inset-x-0 h-1 bg-gradient-to-r from-transparent via-[#3FA85B] to-transparent transform scale-x-0 group-hover:scale-x-100 transition-transform duration-500" />
              </motion.div>
            );
          })}
        </div>

        {/* Realtime Terminal Banner */}
        <div className="mt-12 p-4 sm:p-6 rounded-2xl bg-[#FAFCFA] border border-slate-200 font-mono text-xs text-slate-600 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <span className="inline-block w-2.5 h-2.5 rounded-full bg-[#3FA85B] animate-ping" />
            <span className="text-slate-900 font-bold">ISIMS Sfax Node:</span>
            <span>All 3 Pillar Laboratories actively reporting data from campus facilities.</span>
          </div>
          <div className="text-[11px] text-[#0F4C2A] bg-[#E8F7EE] px-3 py-1 rounded-md border border-[#3FA85B]/30 font-bold">
            SYNC STATUS: NOMINAL
          </div>
        </div>
      </div>
    </section>
  );
};
