import { PillarData, Project, EventItem, TelemetryStat, SponsorTier, TeamMember } from '@/types';

export const PILLARS_DATA: Record<string, PillarData> = {
  exclusion: {
    id: 'exclusion',
    code: '01',
    title: 'Zero Exclusion',
    subTitle: 'Universal Access & Inclusive Technology',
    tagline: 'Nobody should be locked out of a classroom, a lab or a screen. We build tools and run free workshops so more people can walk in.',
    description:
      'We build tech that everyone can use, run open bootcamps for young people who never got the chance, and change designs that quietly shut people out.',
    color: {
      primary: '#06B6D4',
      glow: 'rgba(6, 182, 212, 0.4)',
      gradient: 'from-cyan-500/30 via-cyan-600/10 to-transparent',
      badge: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
      accent: '#0891B2',
      border: 'border-cyan-500/40',
    },
    manifesto: {
      headline: 'Nobody should be locked out of a classroom, a lab or a screen.',
      coreProblem:
        'People with disabilities, neurodivergent learners, and marginalized students are often shut out of digital interfaces and tech opportunities.',
      ourSolution:
        'We build tech that everyone can use, run open bootcamps for young people who never got the chance, and change designs that quietly shut people out.',
      quote: '“Inclusion is making a new space for all.”',
    },
    metrics: [
      { label: 'Youth Trained in Tech', value: '520', suffix: '+', trend: 'From rural regions' },
      { label: 'Assistive Tech Prototypes', value: '9', suffix: ' Built', trend: 'Open hardware' },
      { label: 'Websites Audited', value: '34', suffix: '', trend: 'WCAG AAA certified' },
      { label: 'Inclusion Mentors', value: '45', suffix: '', trend: 'ISIMS Volunteers' },
    ],
    focusAreas: [
      {
        title: 'Universal Digital Access',
        desc: 'Tunisian Sign Language ML and interfaces that are easy to read and use.',
        iconName: 'Eye',
      },
      {
        title: 'Free Open Bootcamps',
        desc: 'Weekend workshops teaching practical digital skills to underserved youth.',
        iconName: 'Compass',
      },
      {
        title: 'Assistive Multimedia Tools',
        desc: 'Accessible web extensions and sensory-friendly interaction tools.',
        iconName: 'HeartHandshake',
      },
    ],
    activeProjectsCount: 6,
  },
  carbon: {
    id: 'carbon',
    code: '02',
    title: 'Zero Carbon',
    subTitle: 'Circular Hardware & Environmental Telemetry',
    tagline: 'Old lab PCs, dead boards, dusty sensors. We give them a second life instead of sending them to the bin.',
    description:
      "We repair, reuse and rebuild before we throw anything away, and we measure our own footprint so we're not just talking.",
    color: {
      primary: '#10B981',
      glow: 'rgba(16, 185, 129, 0.4)',
      gradient: 'from-emerald-500/30 via-emerald-600/10 to-transparent',
      badge: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
      accent: '#059669',
      border: 'border-emerald-500/40',
    },
    manifesto: {
      headline: 'Old lab PCs, dead boards, dusty sensors. We give them a second life.',
      coreProblem:
        'Campuses consume massive energy and generate e-waste from computer labs without real-time tracking.',
      ourSolution:
        "We repair, reuse and rebuild before we throw anything away, and we measure our own footprint so we're not just talking.",
      quote: '“Action begins on campus grounds.”',
    },
    metrics: [
      { label: 'CO2 Offset Estimated', value: '3.8', suffix: ' Tons', trend: 'Monitored via IoT' },
      { label: 'E-Waste Reclaimed', value: '480', suffix: ' kg', trend: 'Reconditioned / Recycled' },
      { label: 'Energy Savings in Labs', value: '22', suffix: '%', trend: 'Smart power schedule' },
      { label: 'Campus Trees Planted', value: '320', suffix: '+', trend: 'In Greater Sfax' },
    ],
    focusAreas: [
      {
        title: 'Open Hardware & IoT',
        desc: 'Low-cost ESP32 solar sensors and second-life e-waste.',
        iconName: 'Cpu',
      },
      {
        title: 'Hardware Circularity Lab',
        desc: 'Refurbishing old lab computers and building Linux stations for local schools.',
        iconName: 'RefreshCw',
      },
      {
        title: 'Solar Rooftop Grid',
        desc: 'Live solar-powered telemetry measuring environmental metrics.',
        iconName: 'Leaf',
      },
    ],
    activeProjectsCount: 7,
  },
  poverty: {
    id: 'poverty',
    code: '03',
    title: 'Zero Poverty',
    subTitle: 'Micro-Funding Tools & Fair Economic Growth',
    tagline: "A good idea shouldn't need a big budget. We test small, honest ways to fund projects that actually help people around us.",
    description:
      'We help students and small local businesses find fair, simple ways to earn, fund and grow.',
    color: {
      primary: '#F59E0B',
      glow: 'rgba(245, 158, 11, 0.4)',
      gradient: 'from-amber-500/30 via-amber-600/10 to-transparent',
      badge: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
      accent: '#D97706',
      border: 'border-amber-500/40',
    },
    manifesto: {
      headline: "A good idea shouldn't need a big budget.",
      coreProblem:
        'Talented students and local small merchants often lack access to honest micro-funding and tools to start.',
      ourSolution:
        'We help students and small local businesses find fair, simple ways to earn, fund and grow.',
      quote: '“Every single human being is born an entrepreneur.” — Prof. Muhammad Yunus',
    },
    metrics: [
      { label: 'Micro-Grants Funded', value: '18', suffix: '+', trend: '+40% this term' },
      { label: 'Student Founders Supported', value: '140', suffix: '+', trend: 'Active cohorts' },
      { label: 'Economic Value Created', value: '45K', suffix: ' TND', trend: 'Community revenue' },
      { label: 'Financial Tech Workshops', value: '24', suffix: '', trend: 'Completed at ISIMS' },
    ],
    focusAreas: [
      {
        title: 'Micro-Funding Tools',
        desc: 'Testing small, honest ways to fund projects and micro-grants that actually help people.',
        iconName: 'Coins',
      },
      {
        title: 'Artisan Digital Onboarding',
        desc: 'Helping local Medina craftspeople bring their work directly online.',
        iconName: 'Users',
      },
      {
        title: 'Student Venture Mentorship',
        desc: 'Practical tools and mentorship to turn ideas into lasting projects.',
        iconName: 'TrendingUp',
      },
    ],
    activeProjectsCount: 5,
  },
};

export const TELEMETRY_STATS: TelemetryStat[] = [
  {
    id: 'members',
    label: 'Active Change-makers',
    value: 280,
    suffix: '+',
    caption: 'Passionate students across Computer Science & Multimedia',
    pillarId: 'general',
  },
  {
    id: 'grants',
    label: 'Venture Capital Disbursed',
    value: 45,
    prefix: '',
    suffix: 'K TND',
    caption: 'Funded across 18 student-led social ventures',
    pillarId: 'poverty',
  },
  {
    id: 'carbon_saved',
    label: 'CO2 Diverted',
    value: 3800,
    suffix: ' kg',
    caption: 'Verified campus footprint reduction through IoT telemetry',
    pillarId: 'carbon',
  },
  {
    id: 'empowered',
    label: 'Lives Impacted',
    value: 1250,
    suffix: '+',
    caption: 'Through accessibility bootcamps, devices, and workshops',
    pillarId: 'exclusion',
  },
];

export const FEATURED_PROJECTS: Project[] = [
  {
    id: 'p-1',
    title: 'Open Hardware Circularity Sprint',
    slug: 'open-hardware-circularity',
    pillarId: 'carbon',
    pillarLabel: 'Zero Carbon',
    status: 'Completed',
    summary: 'We refurbished 42 old lab computers and gave them to schools in rural areas.',
    impactScore: '42 computers donated',
    leadStudent: 'Mariem Ben Salem',
    techStack: ['Linux OS', 'Hardware Repair', 'Open Hardware'],
    metricsAchieved: '42 Computers Restored',
    githubUrl: 'https://github.com/3-zero-isims/greenlab',
    coverGradient: 'from-emerald-950 via-emerald-900 to-black',
  },
  {
    id: 'p-2',
    title: 'SignStream 48h Accessibility Jam',
    slug: 'signstream-accessibility-jam',
    pillarId: 'exclusion',
    pillarLabel: 'Zero Exclusion',
    status: 'Active',
    summary: 'In two days we built the first version of a Tunisian Sign Language translator and tested it with people who use sign language.',
    impactScore: 'Tested with sign language users',
    leadStudent: 'Nour Bouaziz',
    techStack: ['MediaPipe', 'WebRTC', 'PyTorch', 'Next.js'],
    metricsAchieved: 'Live Prototype Built in 48h',
    githubUrl: 'https://github.com/3-zero-isims/signstream',
    demoUrl: '#',
    coverGradient: 'from-cyan-950 via-cyan-900 to-black',
  },
  {
    id: 'p-3',
    title: 'Medina Artisan Digital Onboarding',
    slug: 'medina-artisan-onboarding',
    pillarId: 'poverty',
    pillarLabel: 'Zero Poverty',
    status: 'Active',
    summary: 'We helped craftspeople in the Medina of Sfax open their first online shops.',
    impactScore: 'Direct online storefronts created',
    leadStudent: 'Ahmed Khemakhem',
    techStack: ['Next.js', 'E-Commerce', 'UI/UX Design'],
    metricsAchieved: 'Local Artisans Online',
    githubUrl: 'https://github.com/3-zero-isims/artisanlink',
    demoUrl: '#',
    coverGradient: 'from-amber-950 via-amber-900 to-black',
  },
  {
    id: 'p-4',
    title: 'Solar Rooftop Node Deployment',
    slug: 'solar-rooftop-node',
    pillarId: 'carbon',
    pillarLabel: 'Zero Carbon',
    status: 'Active',
    summary: 'A solar sensor on campus that sends live data on temperature and air quality.',
    impactScore: 'Real-time telemetry live',
    leadStudent: 'Aziz Charfi',
    techStack: ['ESP32', 'Solar Energy', 'MQTT', 'InfluxDB'],
    metricsAchieved: 'Campus Rooftop Deployment',
    githubUrl: 'https://github.com/3-zero-isims/ecosense-iot',
    coverGradient: 'from-teal-950 via-emerald-950 to-black',
  },
  {
    id: 'p-5',
    title: 'Inclusive UI/UX Campus Sprint',
    slug: 'inclusive-uiux-sprint',
    pillarId: 'exclusion',
    pillarLabel: 'Zero Exclusion',
    status: 'Completed',
    summary: 'We reviewed campus web pages and fixed the parts that were hard to read or use.',
    impactScore: 'Enhanced accessibility for students',
    leadStudent: 'Nour Bouaziz',
    techStack: ['WCAG Guidelines', 'Web Accessibility', 'Tailwind CSS'],
    metricsAchieved: 'Campus Sites Audited & Fixed',
    githubUrl: 'https://github.com/3-zero-isims/voxtact',
    coverGradient: 'from-indigo-950 via-cyan-950 to-black',
  },
];

export const UPCOMING_EVENTS: EventItem[] = [
  {
    id: 'ev-1',
    title: 'Tunisian Sign Language ML Workshop',
    type: 'Workshop',
    pillarId: 'exclusion',
    date: 'OCT 24, 2026',
    time: '14:00 - 18:00 GMT+1',
    location: 'ISIMS Multimedia Lab 2',
    seatsTotal: 40,
    seatsRemaining: 12,
    speakerOrLead: 'Nour Bouaziz & AI Team',
    description: 'Train a small model that recognises Tunisian Sign Language. No AI experience needed.',
    isUpcoming: true,
  },
  {
    id: 'ev-2',
    title: 'Circular IoT & Solar ESP32 Hack',
    type: 'Hackathon',
    pillarId: 'carbon',
    date: 'NOV 08, 2026',
    time: '09:00 - 18:00 GMT+1',
    location: 'ISIMS Hardware Lab',
    seatsTotal: 50,
    seatsRemaining: 15,
    speakerOrLead: 'Aziz Charfi & Hardware Team',
    description: "Build a solar-powered sensor from parts we'd otherwise throw away.",
    isUpcoming: true,
  },
  {
    id: 'ev-3',
    title: 'Campus Social Venture Pitch Night',
    type: 'Symposium',
    pillarId: 'poverty',
    date: 'NOV 22, 2026',
    time: '14:00 - 19:00 GMT+1',
    location: 'ISIMS Innovation Space',
    seatsTotal: 80,
    seatsRemaining: 24,
    speakerOrLead: 'Ahmed Khemakhem & Mentors',
    description: 'Pitch a project that helps people, and get honest feedback from mentors.',
    isUpcoming: true,
  },
  {
    id: 'ev-4',
    title: 'Architecture for Decarbonized Code',
    type: 'Tech Talk',
    pillarId: 'carbon',
    date: 'DEC 05, 2026',
    time: '10:00 - 13:00 GMT+1',
    location: 'ISIMS Main Auditorium',
    seatsTotal: 100,
    seatsRemaining: 38,
    speakerOrLead: 'Youssef Triki',
    description: 'How to write and host software that uses less energy.',
    isUpcoming: true,
  },
];

export const SPONSOR_TIERS: SponsorTier[] = [
  {
    id: 'pillar_champion',
    name: 'Pillar Patron',
    investment: '5,000+ TND / yr',
    featured: true,
    color: '#3FA85B',
    benefits: [
      'Main sponsor of our flagship hackathon',
      'Speaking slot and jury seat at our big events',
      'Priority access to top engineering and design students',
      'Your logo on our site, shirts and event materials',
      'Direct link to our Zero Poverty projects',
    ],
    ctaLabel: 'Become a Pillar Patron',
  },
  {
    id: 'innovation_partner',
    name: 'Innovation Partner',
    investment: '2,500 TND / yr',
    featured: false,
    color: '#06B6D4',
    benefits: [
      'Host a technical workshop or mentoring session',
      'Sponsor one hackathon prize or track',
      'Logo on the website and event banner',
      'Early access to student teams for internships',
    ],
    ctaLabel: 'Partner With Us',
  },
  {
    id: 'community_supporter',
    name: 'Seed Supporter',
    investment: '1,000 TND / yr',
    featured: false,
    color: '#F59E0B',
    benefits: [
      'Fund hardware kits and materials for student teams',
      'Logo on our website and project pages',
      'Invitation to demo days and pitch nights',
    ],
    ctaLabel: 'Fund a Student Project',
  },
];

export const CLUB_CORE_TEAM: TeamMember[] = [
  {
    name: 'Youssef Triki',
    role: 'Club President & Lead Architect',
    department: 'Software & Cloud Engineering student. Keeps the whole club pointed in the same direction and designs how our projects fit together.',
    avatarInitials: 'YT',
  },
  {
    name: 'Mariem Ben Salem',
    role: 'Zero Net Carbon Pillar Lead',
    department: 'Runs our recycling and energy projects, and makes sure every build has a low-carbon plan.',
    avatarInitials: 'MB',
  },
  {
    name: 'Ahmed Khemakhem',
    role: 'Zero Poverty & FinTech Lead',
    department: 'Works on micro-funding ideas and simple money tools for students and small businesses.',
    avatarInitials: 'AK',
  },
  {
    name: 'Nour Bouaziz',
    role: 'Zero Exclusion & Accessibility Lead',
    department: 'Human-Computer Interaction & AI. Makes sure what we build works for people with different needs.',
    avatarInitials: 'NB',
  },
  {
    name: 'Aziz Charfi',
    role: 'Head of Hardware & FabLab Prototyping',
    department: 'Runs the lab, the soldering iron and the parts bin.',
    avatarInitials: 'AC',
  },
  {
    name: 'Sarra Guermazi',
    role: 'Community Growth & Hackathon Director',
    department: 'Brings people in, plans our events and keeps them running smoothly.',
    avatarInitials: 'SG',
  },
];

export const FAQS = [
  {
    q: 'Who can join the 3-Zero ISIMS Campus Club?',
    a: 'Any enrolled student at ISIMS (Computer Science, Multimedia, Networks, AI, Master programs) as well as cross-faculty collaborators from the University of Sfax. We welcome coders, designers, communicators, and social activists.',
  },
  {
    q: 'How does the 3-Zero concept work?',
    a: 'Inspired by Nobel Peace Laureate Muhammad Yunus, 3-Zero is a global youth movement committed to achieving: Zero Poverty, Zero Unemployment/Exclusion, and Zero Net Carbon Emissions. Our ISIMS club brings this vision to life through technology and grassroots campus innovation.',
  },
  {
    q: 'Can companies or alumni sponsor specific student projects?',
    a: 'Yes! Sponsors can direct their contributions to dedicated pillars (e.g., funding IoT sensors for Zero Carbon or micro-grants for Zero Poverty) with full transparency and telemetry updates.',
  },
  {
    q: 'Are projects open source?',
    a: 'Yes. All software repositories and hardware schematics built by the club are licensed under open licenses (MIT/GPL/CERN) so other university chapters can deploy them worldwide.',
  },
];
