import { UpcomingEvent, PastEventArchive } from '@/types/events';

export const FEATURED_EVENT: UpcomingEvent = {
  id: 'sfax-3zero-hackathon-2026',
  slug: 'sfax-3zero-hackathon',
  title: 'Sfax 3-Zero Campus Hackathon 2026',
  tagline: '48 Hours of open-source building for Zero Carbon and Zero Exclusion',
  category: 'Hackathon',
  pillarId: 'all',
  startUtc: '2026-10-24T08:30:00Z',
  endUtc: '2026-10-26T18:00:00Z',
  displayDate: 'OCTOBER 24 – 26, 2026',
  displayTime: '48h sprint',
  location: {
    venue: 'Higher Institute of Computer Science & Multimedia (ISIMS)',
    city: 'Sfax, Tunisia',
  },
  coverImage: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
  description:
    'Our biggest event of the year. More than 150 students will team up in mixed groups of coders, hardware people and designers to build working prototypes: reused e-waste, solar sensors and accessible interfaces.',
  speakersOrLeads: [
    { name: 'Youssef Triki', role: 'Club President & Lead Architect' },
    { name: 'Mariem Ben Salem', role: 'Zero Net Carbon Pillar Lead' },
    { name: 'Nour Bouaziz', role: 'Zero Exclusion & Accessibility Lead' },
  ],
  seatsTotal: 150,
  seatsRemaining: 24,
  ticketStatus: 'closing-soon',
  barcodeNumber: '3ZERO-ISIMS-2026-HK88',
  requirements: [
    'Laptop & prototyping kit (if hardware track)',
    'ISIMS or Tunisian university student ID',
    'GitHub / GitLab account',
  ],
  isFeatured: true,
};

export const UPCOMING_EVENTS: UpcomingEvent[] = [
  {
    id: 'ai-gesture-sign-workshop',
    slug: 'ai-gesture-sign-workshop',
    title: 'Tunisian Sign Language ML Workshop',
    tagline: 'Train a small model that recognises Tunisian Sign Language. No AI experience needed.',
    category: 'Workshop',
    pillarId: 'exclusion',
    startUtc: '2026-11-07T13:00:00Z',
    endUtc: '2026-11-07T17:30:00Z',
    displayDate: 'NOVEMBER 07, 2026',
    displayTime: '13:00 – 17:30 UTC+1',
    location: {
      venue: 'ISIMS Multimedia Lab 3',
      city: 'Sfax, Tunisia',
    },
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    description:
      'Train a small model that recognises Tunisian Sign Language. No AI experience needed.',
    speakersOrLeads: [
      { name: 'Nour Bouaziz', role: 'Zero Exclusion & Accessibility Lead' },
    ],
    seatsTotal: 40,
    seatsRemaining: 7,
    ticketStatus: 'closing-soon',
    barcodeNumber: '3ZERO-WS-2026-TSL09',
  },
  {
    id: 'circular-esp32-solar-jam',
    slug: 'circular-esp32-solar-jam',
    title: 'Circular IoT & Solar ESP32 Hack',
    tagline: "Build a solar-powered sensor from parts we'd otherwise throw away.",
    category: 'Fieldwork',
    pillarId: 'carbon',
    startUtc: '2026-11-18T10:00:00Z',
    endUtc: '2026-11-18T16:00:00Z',
    displayDate: 'NOVEMBER 18, 2026',
    displayTime: '10:00 – 16:00 UTC+1',
    location: {
      venue: 'ISIMS Rooftop Lab & Hardware Bench',
      city: 'Sfax, Tunisia',
    },
    coverImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    description:
      "Build a solar-powered sensor from parts we'd otherwise throw away.",
    speakersOrLeads: [
      { name: 'Aziz Charfi', role: 'Head of Hardware & FabLab Prototyping' },
    ],
    seatsTotal: 35,
    seatsRemaining: 18,
    ticketStatus: 'open',
    barcodeNumber: '3ZERO-IOT-2026-SOL14',
  },
  {
    id: 'yunus-micro-grant-pitch',
    slug: 'yunus-micro-grant-pitch',
    title: 'Campus Social Venture Pitch Night',
    tagline: 'Pitch a project that helps people, and get honest feedback from mentors.',
    category: 'Symposium',
    pillarId: 'poverty',
    startUtc: '2026-12-04T15:00:00Z',
    endUtc: '2026-12-04T19:30:00Z',
    displayDate: 'DECEMBER 04, 2026',
    displayTime: '15:00 – 19:30 UTC+1',
    location: {
      venue: 'Sfax Technopark Auditorium',
      city: 'Sfax, Tunisia',
    },
    coverImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80',
    description:
      'Pitch a project that helps people, and get honest feedback from mentors.',
    speakersOrLeads: [
      { name: 'Ahmed Khemakhem', role: 'Zero Poverty & FinTech Lead' },
    ],
    seatsTotal: 90,
    seatsRemaining: 0,
    ticketStatus: 'waitlist',
    barcodeNumber: '3ZERO-SYM-2026-PITCH99',
  },
  {
    id: 'ethical-software-architecture-talk',
    slug: 'ethical-software-architecture-talk',
    title: 'Architecture for Decarbonized Code',
    tagline: 'How to write and host software that uses less energy.',
    category: 'Tech Talk',
    pillarId: 'carbon',
    startUtc: '2026-12-12T14:00:00Z',
    endUtc: '2026-12-12T16:30:00Z',
    displayDate: 'DECEMBER 12, 2026',
    displayTime: '14:00 – 16:30 UTC+1',
    location: {
      venue: 'ISIMS Main Amphithéâtre',
      city: 'Sfax, Tunisia',
    },
    coverImage: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80',
    description:
      'How to write and host software that uses less energy.',
    speakersOrLeads: [
      { name: 'Youssef Triki', role: 'Club President & Lead Architect' },
    ],
    seatsTotal: 100,
    seatsRemaining: 42,
    ticketStatus: 'open',
    barcodeNumber: '3ZERO-TALK-2026-GREEN01',
  },
];

export const PAST_EVENTS_ARCHIVE: PastEventArchive[] = [
  {
    id: 'past-campus-clean-day-2026',
    title: 'ISIMS Campus Clean Day & Green Initiative',
    year: '2026',
    dateFormatted: 'Apr 2026',
    category: 'Fieldwork',
    pillarId: 'carbon',
    attendeeCount: 45,
    recap: 'Mobilized ISIMS students and faculty volunteers for a comprehensive campus clean-up, green space restoration, and waste separation action under the 3-Zero mission.',
    coverImage: '/events/clean-day/clean-day-group.jpg',
    location: 'ISIMS Campus Grounds & Courtyard',
    projectHighlightsCount: 3,
    galleryImages: [
      { url: '/events/clean-day/clean-day-group.jpg', altText: '3-Zero ISIMS student & faculty volunteer squad in campus courtyard' },
      { url: '/events/clean-day/clean-day-action.jpg', altText: 'Volunteers collecting litter and clearing campus green areas' },
      { url: '/events/clean-day/clean-day-selfie.jpg', altText: 'Student volunteer team selfie with cleaning equipment' },
      { url: '/events/clean-day/clean-day-campus.jpg', altText: 'Campus perimeter clean-up and waste station management' },
      { url: '/events/clean-day/clean-day-tree.jpg', altText: 'Campus garden olive tree maintenance and weeding' },
    ],
    highlights: [
      'Over 120kg of recyclables and waste collected across ISIMS campus grounds',
      'Campus garden restoration including weeding and maintenance around historic olive trees',
      'Cross-departmental participation uniting students, club members, and faculty staff',
    ],
  },
  {
    id: 'past-regional-ecofest-talk-2026',
    title: 'Regional EcoFest: Green Tech & Sustainability Summit',
    year: '2026',
    dateFormatted: 'Mar 2026',
    category: 'Tech Talk',
    pillarId: 'carbon',
    attendeeCount: 95,
    recap: 'Convened regional sustainability experts, green tech engineers, and academic researchers for keynote discussions on renewable energy transitions, climate innovation, and circular campus technology.',
    coverImage: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80',
    location: 'ISIMS Main Auditorium',
    projectHighlightsCount: 4,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80', altText: 'Keynote panel discussion with regional experts' },
      { url: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80', altText: 'Auditorium attendees and Q&A session' },
      { url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80', altText: 'Student tech demo showcase' },
    ],
    highlights: [
      'Featured 5 distinguished guest speakers from regional clean-tech and environmental organizations',
      'Over 95 student builders, faculty, and innovators in attendance across keynote and panel tracks',
      'Presented the 3-Zero roadmap for open-source environmental monitoring and campus decarbonization',
    ],
  },
  {
    id: 'past-social-lean-canvas-2026',
    title: 'Social Lean Canvas: Eco-Entrepreneurship Masterclass',
    year: '2026',
    dateFormatted: 'Feb 25, 2026',
    category: 'Workshop',
    pillarId: 'poverty',
    attendeeCount: 65,
    recap: 'Specialized masterclass led by Iyed Zarrougui on mastering the 9 blocks of the Social Lean Canvas, bridging the gap between ecological impact, business viability, and financial sustainability.',
    coverImage: '/events/social-lean-canvas.jpg',
    location: 'ISIMS Campus',
    projectHighlightsCount: 3,
    galleryImages: [
      { url: '/events/social-lean-canvas.jpg', altText: 'Social Lean Canvas Masterclass Official Poster with Speaker Iyed Zarrougui' },
    ],
    highlights: [
      'Strategic Structuring: Mastered the 9 essential blocks of the Social Lean Canvas model',
      'Eco-Entrepreneurship: Bridged the gap between environmental ecology and venture profitability',
      'Led by Iyed Zarrougui: Engineer, Founder of CARBOTRACK, PEES Innovative & Google Cloud Digital Leader',
    ],
  },
  {
    id: 'past-integration-opening-day-2026',
    title: 'ISIMS Integration Day & 3-Zero Club Expo',
    year: '2026',
    dateFormatted: 'Feb 18, 2026',
    category: 'Fieldwork',
    pillarId: 'all',
    attendeeCount: 120,
    recap: 'Campus opening and integration day welcoming new ISIMS students with hands-on club recruitment booths, interactive hardware demos, multi-screen simulators, and problem-solving workshops.',
    coverImage: '/events/integration-day/integration-day-booth.jpg',
    location: 'ISIMS Main Hall & Classrooms',
    projectHighlightsCount: 3,
    galleryImages: [
      { url: '/events/integration-day/integration-day-booth.jpg', altText: '3-Zero ISIMS welcome booth with custom PC showcase and Social Lean Canvas preview' },
      { url: '/events/integration-day/integration-day-sim.jpg', altText: 'Interactive multi-screen simulation station at the club recruitment expo' },
      { url: '/events/integration-day/integration-day-teams.jpg', altText: 'Student teams collaborating on sustainability problem statements, pains, gains, and impact' },
    ],
    highlights: [
      'Over 120 students onboarded and registered for 3-Zero campus cohorts and sprints',
      'Interactive tech showcase featuring custom PC workstations and multi-screen simulators',
      'Hands-on ideation workshop tackling real student sustainability challenges on whiteboard',
    ],
  },
  {
    id: 'past-sign-language-hack-2025',
    title: 'SignStream 48h Accessibility Jam',
    year: '2025',
    dateFormatted: 'Dec 2025',
    category: 'Hackathon',
    pillarId: 'exclusion',
    attendeeCount: 110,
    recap: 'Built and benchmarked the first open dataset for Tunisian Sign Language with 12,000 verified gesture recordings.',
    coverImage: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80',
    location: 'Amphi ISIMS',
    projectHighlightsCount: 6,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80', altText: 'Hackathon presentation hall' },
      { url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80', altText: 'Computer vision testing' },
    ],
    highlights: [
      '12,000 verified video samples collected for Tunisian Sign Language',
      'Over 20 student teams shipped working real-time web prototypes',
    ],
  },
  {
    id: 'past-micro-entrepreneurship-summit-2025',
    title: 'Yunus Social Business Youth Summit',
    year: '2025',
    dateFormatted: 'Oct 2025',
    category: 'Symposium',
    pillarId: 'poverty',
    attendeeCount: 140,
    recap: 'Keynote panels and venture coaching sessions on microfinance and zero-poverty campus innovation with international Yunus Centre speakers.',
    coverImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80',
    location: 'Sfax Technopark',
    projectHighlightsCount: 8,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80', altText: 'Keynote auditorium' },
      { url: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80', altText: 'Mentorship tables' },
    ],
    highlights: [
      '140 attendees across 6 academic institutions in Sfax and Tunis',
      '3 student social startups received first-round seed micro-grants',
    ],
  },
  {
    id: 'past-decarb-web-jam-2025',
    title: 'Green Web Architecture Ideathon',
    year: '2025',
    dateFormatted: 'Jun 2025',
    category: 'Ideation Jam',
    pillarId: 'carbon',
    attendeeCount: 65,
    recap: 'Benchmarked static site generation, WASM micro-frontends, and lightweight image codecs to reduce page weight below 200KB.',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    location: 'Lab Infotel 2',
    projectHighlightsCount: 4,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80', altText: 'Performance profiling graphs' },
    ],
    highlights: [
      'Demonstrated 70% decrease in server compute emissions for student apps',
      'Produced an open guide for energy-efficient Next.js setups',
    ],
  },
  {
    id: 'past-tactile-maps-sprint-2025',
    title: 'Tactile Campus Maps 3D Print Jam',
    year: '2025',
    dateFormatted: 'Apr 2025',
    category: 'Workshop',
    pillarId: 'exclusion',
    attendeeCount: 50,
    recap: 'CAD modeling and 3D printing of high-contrast tactile architectural floor maps for visually impaired students navigating ISIMS.',
    coverImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    location: 'FabLab ISIMS',
    projectHighlightsCount: 3,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80', altText: '3D printing bed with braille tiles' },
    ],
    highlights: [
      'Printed 6 tactile navigation maps installed at campus building entries',
      'Braille labels co-designed with student representatives',
    ],
  },
];
