import { UpcomingEvent, PastEventArchive } from '@/types/events';

export const FEATURED_EVENT: UpcomingEvent = {
  id: 'sfax-3zero-hackathon-2026',
  slug: 'sfax-3zero-hackathon',
  title: 'Sfax 3-Zero Campus Hackathon 2026',
  tagline: '48 Hours of open-source building for Zero Carbon and Zero Exclusion',
  category: 'Hackathon',
  pillarId: 'all',
  startUtc: '2026-10-24T08:30:00Z',
  endUtc: '2026-10-26T18:00:00Z',
  displayDate: 'OCTOBER 24 – 26, 2026',
  displayTime: '48h sprint',
  location: {
    venue: 'Higher Institute of Computer Science & Multimedia (ISIMS)',
    city: 'Sfax, Tunisia',
  },
  coverImage: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
  description:
    'Our biggest event of the year. More than 150 students will team up in mixed groups of coders, hardware people and designers to build working prototypes: reused e-waste, solar sensors and accessible interfaces.',
  speakersOrLeads: [
    { name: 'Youssef Triki', role: 'Club President & Lead Architect' },
    { name: 'Mariem Ben Salem', role: 'Zero Net Carbon Pillar Lead' },
    { name: 'Nour Bouaziz', role: 'Zero Exclusion & Accessibility Lead' },
  ],
  seatsTotal: 150,
  seatsRemaining: 24,
  ticketStatus: 'closing-soon',
  barcodeNumber: '3ZERO-ISIMS-2026-HK88',
  requirements: [
    'Laptop & prototyping kit (if hardware track)',
    'ISIMS or Tunisian university student ID',
    'GitHub / GitLab account',
  ],
  isFeatured: true,
};

export const UPCOMING_EVENTS: UpcomingEvent[] = [
  {
    id: 'ai-gesture-sign-workshop',
    slug: 'ai-gesture-sign-workshop',
    title: 'Tunisian Sign Language ML Workshop',
    tagline: 'Train a small model that recognises Tunisian Sign Language. No AI experience needed.',
    category: 'Workshop',
    pillarId: 'exclusion',
    startUtc: '2026-11-07T13:00:00Z',
    endUtc: '2026-11-07T17:30:00Z',
    displayDate: 'NOVEMBER 07, 2026',
    displayTime: '13:00 – 17:30 UTC+1',
    location: {
      venue: 'ISIMS Multimedia Lab 3',
      city: 'Sfax, Tunisia',
    },
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    description:
      'Train a small model that recognises Tunisian Sign Language. No AI experience needed.',
    speakersOrLeads: [
      { name: 'Nour Bouaziz', role: 'Zero Exclusion & Accessibility Lead' },
    ],
    seatsTotal: 40,
    seatsRemaining: 7,
    ticketStatus: 'closing-soon',
    barcodeNumber: '3ZERO-WS-2026-TSL09',
  },
  {
    id: 'circular-esp32-solar-jam',
    slug: 'circular-esp32-solar-jam',
    title: 'Circular IoT & Solar ESP32 Hack',
    tagline: "Build a solar-powered sensor from parts we'd otherwise throw away.",
    category: 'Fieldwork',
    pillarId: 'carbon',
    startUtc: '2026-11-18T10:00:00Z',
    endUtc: '2026-11-18T16:00:00Z',
    displayDate: 'NOVEMBER 18, 2026',
    displayTime: '10:00 – 16:00 UTC+1',
    location: {
      venue: 'ISIMS Rooftop Lab & Hardware Bench',
      city: 'Sfax, Tunisia',
    },
    coverImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    description:
      "Build a solar-powered sensor from parts we'd otherwise throw away.",
    speakersOrLeads: [
      { name: 'Aziz Charfi', role: 'Head of Hardware & FabLab Prototyping' },
    ],
    seatsTotal: 35,
    seatsRemaining: 18,
    ticketStatus: 'open',
    barcodeNumber: '3ZERO-IOT-2026-SOL14',
  },
  {
    id: 'yunus-micro-grant-pitch',
    slug: 'yunus-micro-grant-pitch',
    title: 'Campus Social Venture Pitch Night',
    tagline: 'Pitch a project that helps people, and get honest feedback from mentors.',
    category: 'Symposium',
    pillarId: 'poverty',
    startUtc: '2026-12-04T15:00:00Z',
    endUtc: '2026-12-04T19:30:00Z',
    displayDate: 'DECEMBER 04, 2026',
    displayTime: '15:00 – 19:30 UTC+1',
    location: {
      venue: 'Sfax Technopark Auditorium',
      city: 'Sfax, Tunisia',
    },
    coverImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80',
    description:
      'Pitch a project that helps people, and get honest feedback from mentors.',
    speakersOrLeads: [
      { name: 'Ahmed Khemakhem', role: 'Zero Poverty & FinTech Lead' },
    ],
    seatsTotal: 90,
    seatsRemaining: 0,
    ticketStatus: 'waitlist',
    barcodeNumber: '3ZERO-SYM-2026-PITCH99',
  },
  {
    id: 'ethical-software-architecture-talk',
    slug: 'ethical-software-architecture-talk',
    title: 'Architecture for Decarbonized Code',
    tagline: 'How to write and host software that uses less energy.',
    category: 'Tech Talk',
    pillarId: 'carbon',
    startUtc: '2026-12-12T14:00:00Z',
    endUtc: '2026-12-12T16:30:00Z',
    displayDate: 'DECEMBER 12, 2026',
    displayTime: '14:00 – 16:30 UTC+1',
    location: {
      venue: 'ISIMS Main Amphithéâtre',
      city: 'Sfax, Tunisia',
    },
    coverImage: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80',
    description:
      'How to write and host software that uses less energy.',
    speakersOrLeads: [
      { name: 'Youssef Triki', role: 'Club President & Lead Architect' },
    ],
    seatsTotal: 100,
    seatsRemaining: 42,
    ticketStatus: 'open',
    barcodeNumber: '3ZERO-TALK-2026-GREEN01',
  },
];

export const PAST_EVENTS_ARCHIVE: PastEventArchive[] = [
  {
    id: 'past-spring-hardware-2026',
    title: 'Open Hardware Circularity Sprint',
    year: '2026',
    dateFormatted: 'May 2026',
    category: 'Fieldwork',
    pillarId: 'carbon',
    attendeeCount: 86,
    recap: 'Repurposed 42 outdated laboratory desktop towers into open-source Linux learning terminals for rural primary schools in Sfax.',
    coverImage: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80',
    location: 'ISIMS Circular Lab',
    projectHighlightsCount: 4,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80', altText: 'Electronics workstation' },
      { url: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80', altText: 'Terminal setup session' },
      { url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80', altText: 'Soldering bench test' },
    ],
    highlights: [
      '42 desktop units restored to working order with lightweight Linux OS',
      'Donated to 3 rural primary schools in the Sfax governorate',
      'Over 60kg of potential electronic e-waste diverted from landfill',
    ],
  },
  {
    id: 'past-accessibility-audit-2026',
    title: 'Inclusive UI/UX Campus Sprint',
    year: '2026',
    dateFormatted: 'Mar 2026',
    category: 'Workshop',
    pillarId: 'exclusion',
    attendeeCount: 72,
    recap: 'Audited 5 public university portals against WCAG AAA standards alongside visually impaired student collaborators.',
    coverImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    location: 'Multimedia Studio ISIMS',
    projectHighlightsCount: 5,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80', altText: 'Screen reader usability testing' },
      { url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80', altText: 'Figma accessibility audit' },
    ],
    highlights: [
      '5 university portals evaluated across 48 WCAG criteria',
      'Published open-source accessibility design guidelines for student portals',
      '12 actionable pull requests submitted to open university web tools',
    ],
  },
  {
    id: 'past-iot-telemetry-deployment-2026',
    title: 'Solar Rooftop Node Deployment',
    year: '2026',
    dateFormatted: 'Feb 2026',
    category: 'Fieldwork',
    pillarId: 'carbon',
    attendeeCount: 45,
    recap: 'Installed 8 solar telemetry beacons across ISIMS campus rooftops monitoring particulate matter and ambient temperature in real time.',
    coverImage: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80',
    location: 'Rooftop Node 01',
    projectHighlightsCount: 2,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80', altText: 'Solar panel beacon assembly' },
      { url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80', altText: 'LoRa gateway test' },
    ],
    highlights: [
      '8 continuous solar monitoring nodes deployed across campus roofs',
      'Open Grafana dashboard streaming live particulate matter metrics',
    ],
  },
  {
    id: 'past-medina-craft-outreach-2026',
    title: 'Medina Artisan Digital Onboarding',
    year: '2026',
    dateFormatted: 'Jan 2026',
    category: 'Fieldwork',
    pillarId: 'poverty',
    attendeeCount: 64,
    recap: 'Integrated direct peer-to-peer digital ordering tools for 28 traditional leather and pottery artisans in the historic Medina of Sfax.',
    coverImage: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80',
    location: 'Medina of Sfax',
    projectHighlightsCount: 3,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80', altText: 'Artisan workshop session' },
      { url: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80', altText: 'Catalog photography' },
    ],
    highlights: [
      '28 craft workshops digitally registered with catalog QR cards',
      'Zero-commission payment integration enabled via local mobile wallets',
    ],
  },
  {
    id: 'past-sign-language-hack-2025',
    title: 'SignStream 48h Accessibility Jam',
    year: '2025',
    dateFormatted: 'Dec 2025',
    category: 'Hackathon',
    pillarId: 'exclusion',
    attendeeCount: 110,
    recap: 'Built and benchmarked the first open dataset for Tunisian Sign Language with 12,000 verified gesture recordings.',
    coverImage: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80',
    location: 'Amphi ISIMS',
    projectHighlightsCount: 6,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80', altText: 'Hackathon presentation hall' },
      { url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80', altText: 'Computer vision testing' },
    ],
    highlights: [
      '12,000 verified video samples collected for Tunisian Sign Language',
      'Over 20 student teams shipped working real-time web prototypes',
    ],
  },
  {
    id: 'past-micro-entrepreneurship-summit-2025',
    title: 'Yunus Social Business Youth Summit',
    year: '2025',
    dateFormatted: 'Oct 2025',
    category: 'Symposium',
    pillarId: 'poverty',
    attendeeCount: 140,
    recap: 'Keynote panels and venture coaching sessions on microfinance and zero-poverty campus innovation with international Yunus Centre speakers.',
    coverImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80',
    location: 'Sfax Technopark',
    projectHighlightsCount: 8,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80', altText: 'Keynote auditorium' },
      { url: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80', altText: 'Mentorship tables' },
    ],
    highlights: [
      '140 attendees across 6 academic institutions in Sfax and Tunis',
      '3 student social startups received first-round seed micro-grants',
    ],
  },
  {
    id: 'past-decarb-web-jam-2025',
    title: 'Green Web Architecture Ideathon',
    year: '2025',
    dateFormatted: 'Jun 2025',
    category: 'Ideation Jam',
    pillarId: 'carbon',
    attendeeCount: 65,
    recap: 'Benchmarked static site generation, WASM micro-frontends, and lightweight image codecs to reduce page weight below 200KB.',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    location: 'Lab Infotel 2',
    projectHighlightsCount: 4,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80', altText: 'Performance profiling graphs' },
    ],
    highlights: [
      'Demonstrated 70% decrease in server compute emissions for student apps',
      'Produced an open guide for energy-efficient Next.js setups',
    ],
  },
  {
    id: 'past-tactile-maps-sprint-2025',
    title: 'Tactile Campus Maps 3D Print Jam',
    year: '2025',
    dateFormatted: 'Apr 2025',
    category: 'Workshop',
    pillarId: 'exclusion',
    attendeeCount: 50,
    recap: 'CAD modeling and 3D printing of high-contrast tactile architectural floor maps for visually impaired students navigating ISIMS.',
    coverImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    location: 'FabLab ISIMS',
    projectHighlightsCount: 3,
    galleryImages: [
      { url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80', altText: '3D printing bed with braille tiles' },
    ],
    highlights: [
      'Printed 6 tactile navigation maps installed at campus building entries',
      'Braille labels co-designed with student representatives',
    ],
  },
];
