import { StaffMember, ExecutiveBoardCohort } from '@/types/staff';

export const CURRENT_BOARD_2025_2026: StaffMember[] = [];

export const FOUNDATION_BOARD_2024_2025: StaffMember[] = [
  {
    id: 'ahmed-fki',
    index: '01',
    name: 'Ahmed Fki',
    firstName: 'Ahmed',
    lastName: 'Fki',
    role: 'Club President',
    department: 'Big Data Licence, ISIMS',
    pillarFocus: 'Core Lead',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Leads chapter strategic direction, university administration relations, and ensures 3-Zero mission alignment across all student cohorts.',
    funFact: 'Co-founded the 3-Zero ISIMS Campus chapter and architected the initial club initiatives.',
    portraitCutout: '/staff/ahmed-fki.jpg',
    fallbackPhoto: '/staff/ahmed-fki.jpg',
    photoType: 'framed',
    mandateYear: 'foundation-team',
    order: 1,
    socials: [
    ],
  },
  {
    id: 'heba-sanaa',
    index: '02',
    name: 'Heba Sanaa',
    firstName: 'Heba',
    lastName: 'Sanaa',
    role: 'Human Ressources Manager',
    department: ' Multimedia Licence, ISIMS',
    pillarFocus: 'Core Lead',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Oversees member onboarding, team wellbeing, cross-cohort collaboration, and talent placement across student projects.',
    funFact: 'Managed the recruitment and integration of over 120 active club members during opening day.',
    portraitCutout: '/staff/whatsapp-image-2026-09-29-at-11-33-28-pm-1790747906866.jpeg',
    fallbackPhoto: '/staff/whatsapp-image-2026-09-29-at-11-33-28-pm-1790747906866.jpeg',
    photoType: 'framed',
    mandateYear: 'foundation-team',
    order: 2,
    socials: [
    ],
  },
  {
    id: 'elyess-bouhlel',
    index: '03',
    name: 'Elyess Bouhlel',
    firstName: 'Elyess',
    lastName: 'Bouhlel',
    role: 'Media Manager',
    department: 'Big Data Licence, ISIMS',
    pillarFocus: 'Core Lead',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Directs digital branding, visual assets, video production, and social media storytelling for all club campaigns.',
    funFact: 'Designs the promotional visual identities, posters, and interactive video reels for chapter events.',
    portraitCutout: '/staff/whatsapp-image-2026-09-29-at-11-33-27-pm-1790748003680.jpeg',
    fallbackPhoto: '/staff/whatsapp-image-2026-09-29-at-11-33-27-pm-1790748003680.jpeg',
    photoType: 'framed',
    mandateYear: 'foundation-team',
    order: 3,
    socials: [
    ],
  },
  {
    id: 'ahmed-bahri',
    index: '04',
    name: 'Ahmed Bahri',
    firstName: 'Ahmed',
    lastName: 'Bahri',
    role: 'Sustainable Campus Manager',
    department: 'Big Data Licence, ISIMS',
    pillarFocus: 'Zero Net Carbon',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Leads sustainable campus operations, green space management, and energy efficiency initiatives across the institute.',
    funFact: 'Spearheaded the ISIMS Campus Clean Day and campus garden restoration project.',
    portraitCutout: '/staff/whatsapp-image-2026-09-29-at-11-33-27-pm--1--1790747827055.jpeg',
    fallbackPhoto: '/staff/whatsapp-image-2026-09-29-at-11-33-27-pm--1--1790747827055.jpeg',
    photoType: 'framed',
    mandateYear: 'foundation-team',
    order: 4,
    socials: [
    ],
  },
  {
    id: 'ameni-dhouib',
    index: '05',
    name: 'Ameni Dhouib',
    firstName: 'Ameni',
    lastName: 'Dhouib',
    role: 'Event & Youth We Can Manager',
    department: 'Software Engineering, ISIMS',
    pillarFocus: 'Zero Exclusion',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Plans and coordinates campus workshops, ideation jams, speaker talks, and youth empowerment initiatives.',
    funFact: 'Organized the Social Lean Canvas Masterclass and Youth We Can community sessions.',
    portraitCutout: '/staff/ameni-dhouib.jpg',
    fallbackPhoto: '/staff/ameni-dhouib.jpg',
    photoType: 'framed',
    mandateYear: 'foundation-team',
    order: 5,
    socials: [
    ],
  },
  {
    id: 'farah-ayedi',
    index: '06',
    name: 'Farah Ayedi',
    firstName: 'Farah',
    lastName: 'Ayedi',
    role: 'Financial and Administratif Manager',
    department: 'Big Data Licence, ISIMS',
    pillarFocus: 'Zero Poverty',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Manages chapter budgeting, administrative approvals, event logistics funding, and partner sponsorship tracking.',
    funFact: 'Keeps all event procurement, supplies, and club financial records meticulously organized.',
    portraitCutout: '/staff/whatsapp-image-2026-09-29-at-11-33-29-pm-1790749692678.jpeg',
    fallbackPhoto: '/staff/whatsapp-image-2026-09-29-at-11-33-29-pm-1790749692678.jpeg',
    photoType: 'framed',
    mandateYear: 'foundation-team',
    order: 6,
    socials: [
    ],
  },
  {
    id: 'habib-zrida',
    index: '07',
    name: 'Habib Zrida',
    firstName: 'Habib',
    lastName: 'Zrida',
    role: 'Financial and Administratif Assistant',
    department: 'ISIMS Student',
    pillarFocus: 'Zero Poverty',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Assists with inventory, financial auditing, procurement of hardware parts, and operational logistics for all sprints.',
    funFact: 'Streamlined logistics during the 3-Zero integration day expo and registration booth.',
    portraitCutout: '/staff/whatsapp-image-2026-09-29-at-11-33-29-pm--1--1790749785983.jpeg',
    fallbackPhoto: '/staff/whatsapp-image-2026-09-29-at-11-33-29-pm--1--1790749785983.jpeg',
    photoType: 'framed',
    mandateYear: 'foundation-team',
    order: 7,
    socials: [
    ],
  },
  {
    id: 'aya-rhouma',
    index: '08',
    name: 'Aya Rhouma',
    firstName: 'Aya',
    lastName: 'Rhouma',
    role: 'Event & Youth We Can Assistant',
    department: 'Software Engineering, ISIMS',
    pillarFocus: 'Zero Exclusion',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Supports event planning, attendee coordination, speaker hospitality, and Youth We Can workshops.',
    funFact: 'Facilitated team ideation and problem-solving exercises during club onboarding sprints.',
    portraitCutout: '/staff/aya-rhouma.jpg',
    fallbackPhoto: '/staff/aya-rhouma.jpg',
    photoType: 'framed',
    mandateYear: 'foundation-team',
    order: 8,
    socials: [
    ],
  },
  {
    id: 'oussema-hachicha',
    index: '09',
    name: 'Oussema Hachicha',
    firstName: 'Oussema',
    lastName: 'Hachicha',
    role: 'Sustainable Campus Assistant',
    department: 'Big Data Licence, ISIMS',
    pillarFocus: 'Zero Net Carbon',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Assists with campus fieldwork, waste audits, recycling initiatives, and hardware setup for eco-sprints.',
    funFact: 'Active coordinator during the campus greening initiative and tree preservation projects.',
    portraitCutout: '/staff/oussema-hachicha.jpg',
    fallbackPhoto: '/staff/oussema-hachicha.jpg',
    photoType: 'framed',
    mandateYear: 'foundation-team',
    order: 9,
    socials: [
    ],
  },
];

export const DEFAULT_STAFF_COHORTS: ExecutiveBoardCohort[] = [
  {
    id: 'foundation-team',
    yearLabel: 'Foundation Team',
    tagline: 'Founding Executive Board',
    isCurrent: true,
    members: FOUNDATION_BOARD_2024_2025,
  },
  {
    id: 'current-team',
    yearLabel: 'Current Team',
    tagline: 'Current Executive Board',
    isCurrent: false,
    members: CURRENT_BOARD_2025_2026,
  },
];

export const staffMembers: StaffMember[] = FOUNDATION_BOARD_2024_2025;


