import { StaffMember, ExecutiveBoardCohort } from '@/types/staff';

export const CURRENT_BOARD_2025_2026: StaffMember[] = [
  {
    id: 'youssef-triki',
    index: '01',
    name: 'Youssef Triki',
    firstName: 'Youssef',
    lastName: 'Triki',
    role: 'Club President & Lead Architect',
    department: 'Software & Cloud Engineering, ISIMS',
    pillarFocus: 'Core Lead',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Software & Cloud Engineering student. Keeps the whole club pointed in the same direction and designs how our projects fit together.',
    funFact: 'Built his first solar-powered Raspberry Pi weather station on the roof of ISIMS in 2nd year.',
    portraitCutout: '/staff/youssef.png',
    fallbackPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    photoType: 'framed',
    mandateYear: '2025-2026',
    order: 1,
    socials: [
      { platform: 'github', url: 'https://github.com' },
      { platform: 'linkedin', url: 'https://linkedin.com' },
      { platform: 'email', url: 'mailto:youssef@isims.tn' },
    ],
  },
  {
    id: 'mariem-ben-salem',
    index: '02',
    name: 'Mariem Ben Salem',
    firstName: 'Mariem',
    lastName: 'Ben Salem',
    role: 'Zero Net Carbon Pillar Lead',
    department: 'Embedded IoT & Environmental Informatics',
    pillarFocus: 'Zero Net Carbon',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Runs our recycling and energy projects, and makes sure every build has a low-carbon plan.',
    funFact: 'Has soldered over 120 custom ESP32 energy-sensing nodes with recycled lithium cells.',
    portraitCutout: '/staff/mariem.png',
    fallbackPhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    photoType: 'framed',
    mandateYear: '2025-2026',
    order: 2,
    socials: [
      { platform: 'github', url: 'https://github.com' },
      { platform: 'linkedin', url: 'https://linkedin.com' },
      { platform: 'twitter', url: 'https://x.com' },
    ],
  },
  {
    id: 'ahmed-khemakhem',
    index: '03',
    name: 'Ahmed Khemakhem',
    firstName: 'Ahmed',
    lastName: 'Khemakhem',
    role: 'Zero Poverty & FinTech Lead',
    department: 'Data Science & Decentralized Systems',
    pillarFocus: 'Zero Poverty',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Works on micro-funding ideas and simple money tools for students and small businesses.',
    funFact: 'Volunteers on weekends teaching algorithmic Python to rural high schoolers.',
    portraitCutout: '/staff/ahmed.png',
    fallbackPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    photoType: 'framed',
    mandateYear: '2025-2026',
    order: 3,
    socials: [
      { platform: 'github', url: 'https://github.com' },
      { platform: 'linkedin', url: 'https://linkedin.com' },
      { platform: 'website', url: 'https://ahmed.dev' },
    ],
  },
  {
    id: 'nour-bouaziz',
    index: '04',
    name: 'Nour Bouaziz',
    firstName: 'Nour',
    lastName: 'Bouaziz',
    role: 'Zero Exclusion & Accessibility Lead',
    department: 'Human-Computer Interaction & AI',
    pillarFocus: 'Zero Exclusion',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Human-Computer Interaction & AI. Makes sure what we build works for people with different needs.',
    funFact: 'Fluent in Tunisian Sign Language (LST) and built a real-time gesture-to-speech mobile translator.',
    portraitCutout: '/staff/nour.png',
    fallbackPhoto: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
    photoType: 'framed',
    mandateYear: '2025-2026',
    order: 4,
    socials: [
      { platform: 'linkedin', url: 'https://linkedin.com' },
      { platform: 'github', url: 'https://github.com' },
      { platform: 'twitter', url: 'https://x.com' },
    ],
  },
  {
    id: 'aziz-charfi',
    index: '05',
    name: 'Aziz Charfi',
    firstName: 'Aziz',
    lastName: 'Charfi',
    role: 'Head of Hardware & FabLab Prototyping',
    department: 'Robotics & Embedded Systems',
    pillarFocus: 'Zero Net Carbon',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Runs the lab, the soldering iron and the parts bin.',
    funFact: '3D-printed a functional quadcopter chassis entirely from shredded campus plastic bottles.',
    portraitCutout: '/staff/aziz.png',
    fallbackPhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    photoType: 'framed',
    mandateYear: '2025-2026',
    order: 5,
    socials: [
      { platform: 'github', url: 'https://github.com' },
      { platform: 'linkedin', url: 'https://linkedin.com' },
    ],
  },
  {
    id: 'sarra-guermazi',
    index: '06',
    name: 'Sarra Guermazi',
    firstName: 'Sarra',
    lastName: 'Guermazi',
    role: 'Community Growth & Hackathon Director',
    department: 'Computer Engineering & Digital Marketing',
    pillarFocus: 'Core Lead',
    quote: "Let's build a Zero Exclusion, Zero Carbon, Zero Poverty world.",
    bio: 'Brings people in, plans our events and keeps them running smoothly.',
    funFact: 'Organized Sfax’s largest inter-university hackathon with 280+ active participants.',
    portraitCutout: '/staff/sarra.png',
    fallbackPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    photoType: 'framed',
    mandateYear: '2025-2026',
    order: 6,
    socials: [
      { platform: 'linkedin', url: 'https://linkedin.com' },
      { platform: 'twitter', url: 'https://x.com' },
      { platform: 'email', url: 'mailto:sarra@isims.tn' },
    ],
  },
];

export const FOUNDATION_BOARD_2024_2025: StaffMember[] = [
  {
    id: 'youssef-triki-founding',
    index: '01',
    name: 'Youssef Triki',
    firstName: 'Youssef',
    lastName: 'Triki',
    role: 'Founding President',
    department: 'Software Engineering, ISIMS',
    pillarFocus: 'Core Lead',
    quote: "Establishing the 3-Zero mission at ISIMS from the ground up.",
    bio: 'Co-founded the 3-Zero Campus Club ISIMS chapter, leading accreditation with Yunus Centre and initial student recruitment.',
    funFact: 'Drafted the initial 3-Zero ISIMS charter during the 2024 winter sprint.',
    portraitCutout: '/staff/youssef.png',
    fallbackPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    photoType: 'framed',
    mandateYear: '2024-2025',
    order: 1,
    socials: [
      { platform: 'github', url: 'https://github.com' },
      { platform: 'linkedin', url: 'https://linkedin.com' },
    ],
  },
  {
    id: 'mariem-ben-salem-founding',
    index: '02',
    name: 'Mariem Ben Salem',
    firstName: 'Mariem',
    lastName: 'Ben Salem',
    role: 'Founding Vice-President',
    department: 'IoT & Environmental Informatics',
    pillarFocus: 'Zero Net Carbon',
    quote: "Building our first campus sustainability benchmarks.",
    bio: 'Pioneered the club FabLab partnership and led our first zero-waste campus audit.',
    funFact: 'Initiated the first campus electronic waste collection drive.',
    portraitCutout: '/staff/mariem.png',
    fallbackPhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    photoType: 'framed',
    mandateYear: '2024-2025',
    order: 2,
    socials: [
      { platform: 'github', url: 'https://github.com' },
      { platform: 'linkedin', url: 'https://linkedin.com' },
    ],
  },
  {
    id: 'ahmed-khemakhem-founding',
    index: '03',
    name: 'Ahmed Khemakhem',
    firstName: 'Ahmed',
    lastName: 'Khemakhem',
    role: 'Founding General Secretary',
    department: 'Decentralized Systems & AI',
    pillarFocus: 'Zero Poverty',
    quote: "Structuring our student projects for lasting community impact.",
    bio: 'Managed club logistics, university relations, and inaugural partnership agreements.',
    funFact: 'Built the first version of the club website.',
    portraitCutout: '/staff/ahmed.png',
    fallbackPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    photoType: 'framed',
    mandateYear: '2024-2025',
    order: 3,
    socials: [
      { platform: 'github', url: 'https://github.com' },
      { platform: 'linkedin', url: 'https://linkedin.com' },
    ],
  },
  {
    id: 'sarra-guermazi-founding',
    index: '04',
    name: 'Sarra Guermazi',
    firstName: 'Sarra',
    lastName: 'Guermazi',
    role: 'Founding Communications Officer',
    department: 'Digital Marketing & Multimedia',
    pillarFocus: 'Core Lead',
    quote: "Spreading the 3-Zero philosophy across the university.",
    bio: 'Led the branding launch, student onboarding campaigns, and inaugural orientation sessions.',
    funFact: 'Designed the original 3-Zero ISIMS visual identity and booth.',
    portraitCutout: '/staff/sarra.png',
    fallbackPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    photoType: 'framed',
    mandateYear: '2024-2025',
    order: 4,
    socials: [
      { platform: 'linkedin', url: 'https://linkedin.com' },
      { platform: 'email', url: 'mailto:sarra@isims.tn' },
    ],
  },
];

export const DEFAULT_STAFF_COHORTS: ExecutiveBoardCohort[] = [
  {
    id: 'foundation-team',
    yearLabel: 'Foundation Team',
    tagline: 'Foundation Team',
    isCurrent: false,
    members: FOUNDATION_BOARD_2024_2025,
  },
  {
    id: 'current-team',
    yearLabel: 'Current Team',
    tagline: 'Current Team',
    isCurrent: true,
    members: CURRENT_BOARD_2025_2026,
  },
];

export const staffMembers: StaffMember[] = CURRENT_BOARD_2025_2026;

